<a href="https://colab.research.google.com/github/NNBtw/tibame20260910/blob/main/tibame20260924_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import urllib.request as req

url = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=38250&geo=TW%2CHK"
f = req.urlopen(url)
content = f.read()
# loads: bytes型態->list/dic型態
content = json.loads(content)
# print(type(content))
# [彈幕{}, 彈幕{}...]
danmus = content["data"]["danmu"]
for d in danmus:
    print(d["userid"], d["text"])

andy475713 1
tcg19648 2024.6.23簽
shackle9487 簽🌭️
naiyu0429 2024/7/3冬雪簽
gtkl20050 為何一直沒法看
robloxaron 2025/8/6首簽!!!
FeiFei88 2025／8／24
efg130 20250802
star112999 20240821 我來啦
cmh0326 2024/7/27 簽 (剛又刷一次刀匠
lkjh4128 台中代表簽
Cwy0831 Sign
f82726 不知道幾刷簽
cpz0426 20262/28簽到
caizhenlzz72 2025/8/1簽
po971030 2024.08.04
baseball2470 簽🌭️
brightwinnn 簽嗚嗚嗚嗚
lspss93011 2025/07/07小史簽
zenyu98 神作留名
cfs10519 簽 2024/8/21
Jayabby666 2024.06.11簽ʕ´•ᴥ•`ʔ
nini1001208 必須簽！
poopoo9999 あります平城山ならゆ
fsh975321 俺沒偷梅吃
Ifffhftg 哈哈
wrxmars 2025.8.11等無限城第二部 簽
Kakashi09182 神作簽簽簽！！！
chachamashum 簽！！！！！
yinyinoby 2026/1/17
supreme888 2025/8/13簽 ε٩(๑> ₃ <)۶з
Ajasmine5678 2024/6/11
hsiao700915 2025/2/6
xin54081 2025 8／25簽！
pinhuah30 ♡
fgbg32112 2025/02/04 簽
s206179 簽
J50223 有夠好看!!
q06974520 簽(⁠⁰⁠▿⁠⁰⁠)⁠
milly0411 20250805 LLL
kang520000 終於來了   簽😍
b4y9vtf99 2025 2刷簽
tsung3689 2025/8/13 簽~
xhbihwsxbi 2025/12/7簽（剛刷完刀匠村）
bluesezero 2024.08.17簽
lo06230917 2025 08 12 首簽 追完直接午夜場imax走起 !!!
fifi4869 2026/3/3簽
p107015 2024/10/26 三刷!
a20116 巴哈我大哥
yuyunhan66 2025/7/29
yuyunhan66 回來複習
yuyunhan66 無限成要上啦
yuxue15 2025/8/15首刷！
chibangnoob 2025 7.5世界末日前在刷一次
jjhaha666 2025/9/11
liyuwei88092 2024/06/29簽
sorapancat 嵌個
jfrwxzmkkw 2024.07.12首刷!!!!!
newer 2025/7/24簽
dingkangr 2025/08/19 坐等第二部
yufanlin09 2025/8/7無限城前複習
jsy0104 2024615簽
Yea1efb5a 2026.6.8簽
Anna15 2025/8/17
Bernie1018 終於啊～
Shwan1023 神作簽到！！！！！
emu9025 2025/8/12簽
dkjkd13 2024/8/2簽
wanyan0803 20258.5簽！
ztdmjbj7s7 2025.08.15坐等無限城第二部
Cathy0811 簽
doalala01 ㄑ
xdxd075806 2025/7/23簽
RubyHsu0208 簽
LKTzu 2024/6/18 簽
peiyun0371 簽簽簽!!
N127513 2025/8/12四刷
super1180 簽
daxin1818 2024/7/11簽
Nick990929 嗚嗚嗚嗚嗚嗚嗚嗚嗚嗚
A20101017 7/14來這裡！炭炭生日快樂🎂
ry7wvypqcb 2024/9/18簽！
andy0310 20250507簽
Yucheng0125 2024.06.29簽
alanakxz 2025/8/22首簽!!!
saul11055054 簽簽簽~~~
lin8596lin 2025.6.2簽
chlooe 簽奧
zigr10 終於來看了啊啊啊 7.13
tshi606eggy 4刷
abcd7849 簽
s43003573 2024/8/3
ajhu0706 2024/7/9
XHJ1104 7/16慶補完全番🥳
petty724 2025/7/26二刷！！！
terry5948787 2025.7.29簽
Lulu0626 2025/8/15 無限城imax根本神
dodylee0107 柱訓練簽到啦
twpopcat0716 簽
liyin0617 義勇寶寶我來了
we9763214 簽
Gh672108 2025/8/4簽
minimina52 20240626簽簽~!!
Xczy11530 2025/8/2 簽
Ilyuri821 ♩
gojowtw 2025.08.25 等無線城二部曲！！！
Miuccia1218 簽簽簽簽簽！
wqx0427 2
c08192009 24/7/25簽
glitter630 2025/8/8簽
ert5945vvv 簽
spf7q 來拉
kcjh1220813 簽！
wannasleep94 20260807
jay139852430 簽💗
shinguji ​
nz779rmv86 2024/7/15簽！
b4y9vtf99 簽啊啊啊啊啊啊啊啊啊
pir0680 二刷!!!
Han2008 2024/7/1簽
yscjj6g8h5 7.4四刷簽
kh69xvvspn 2024/7/31晴姊簽🐣
lin8596lin 2024.10.26簽
kumasuki8365 2024/07/23 首刷
zie1219grvi 簽

a123423546 四刷
Samber990 2025/8/10 簽！
moonisme 最神op 要來嘍
as127261535 12345678910
BHSN00000f8q 無一郎
fishyunn306 24 7 18！！！
s109071 一进来就那么多弹幕
Ting990802 為什麼我星期日晚上才知道有新的啊啊啊啊
mic0 2025/8/15
oo555555555 幹
Cwy0831 20240630
s0153444 2025/8/22！簽
cn5t9z2br5 看完結局再回來看(;´༎ຶД༎ຶ`)
ghfj1311317 25445345348
ufggfg ,裡面有沒有蔡徐坤啊
duck1005 2025/3/1
tyuko21 電影前複習
xssh2025 急死我了
jimmylee0427 2025.08.24 簽
WWWfff1234 2025/11/26
j39873974 簽RRRR
Nini1129 啊啊啊
uglyggyy 我已急到要開斑紋了
laiyichen912 2024/7/19 簽
baseball2470 簽奧
Rose11281115 2025/8/10簽
Clair0514 原來是這樣發彈幕
serendipityx 簽簽簽
rayhao1103 我哥說彈幕很好笑
yourrenfly 2024.7.31 登記分發 補簽！
eagk 2025/8/28簽
m29296603 6刷2024/11/10
arvin200903 你好 我叫艾文
Joanna710 啊啊啊！無一狼我來了！
jchdxh 2025\9\28 簽
sunnyo0610 啊啊啊啊
edwardxup6 2025/07/02簽
carrielin90 2025.02.10簽！！
yunilc77 2024730簽
nikki0413 哈哈哈哈哈哈哈哈
djduzg 不愧是幽浮社
XHJ1104 久違東西終於迎來第一場
linlin818 無限刷
more850202 二刷
vz2885379 二刷二刷
junyanc984 2025/9/5簽到
Dravo41973 20241013
Hello1017 無限城
harperlee 簽
dopg853186 巴哈我大哥
Cherry0439 20250815簽
Peiqe 2025 8 24
cchenwei1119 2024.6.30
minchunpeng 20240805簽
mia0902 愛死透透了~
lin7329 耶
AZ1239 嗨
Asd820322 來重刷
verybigdick 20240101簽
joyceph2579 耶耶耶來了來了~
BHSN00003alj 2024.8.4
LZWSophia 2024.6.22
medaggman 2024/7/16簽
Justine819 2025/8/20 簽
Kitty167 !
Edward0416 無限城上映前複習+1
aa20091009 2024/7/3
st841513 哈哈
dodylee0107 小忍忍我來了
as127261535 0.0
ufggfg 蔡徐坤蔡徐坤
high7887 20240620簽
vifanli 哈哈哈
kainingh704 2024  11/8 簽簽 期待
xxzbkrkthq 無限城看完再複習
xxzbkrkthq 20250824
qwe20229368 從第一集看到柱訓練篇 期待無限城3部曲
suuu0504 開槍的不要 悄悄地進村
areusick 簽！(⁠◍⁠•⁠ᴗ⁠•⁠◍⁠)⁠❤
ruxuan0318 2025.8/13簽
michael96 28/7/2025 簽
tsaievy0407 2025.8.22
doggod 3
f350135 2025825首看!!
j8xs7vwrtn 2025/8/30
ssesw 2025/11/26
ytchengs1 簽
XIANbei55 無敵
XHJ1104 俗話：開始及為結束😃😃
tai1020326 2025.08.19簽
Rrtyuui92 我爹你們
mashumao96 已經三刷了
Coffee3759 有JOJO即視感
gg432 無一郎寶寶，我來了
sed970731 大便
Rita6146 昨天看完無限城第一張了
dodylee0107 義勇我也來了
monkeyqqq 2025/11/29
caizhenlzz72 2025/8/1三刷
anniya411 2025/8/18
super1180 簽爆
rainbing356 2025.10.20首簽💜
imlilian Lilian
tswm7vmspv 期待
j437 2300.13.31
lin8596lin 2024.10.25簽
yupeko0525 歐買尬 我的實彌🫦🫦
rochat0875 嘿嘿嘿
lst20079 ❤️❤️
a18924842451 Aaaaaaaaaa
nervous0304 2025/10/18
ufggfg 啊這不是我在店裡看到了嗎
psycho12345 喔後
ty9pfc5hdt 喔！！我的不死川老公！
alicexyz2021 蛇蛇真的喜歡站高點
line1031229 伊黑寶寶啊啊啊啊
ms0264093 二刷~~~
tim061801 高潮了
zxx424z229 2024/6/30 畢業快樂
jellyQAQfish 2024/813刷的第五次
atmp7689 2024/11/1簽
milu1115 20250808
Chunlin0912 2025818
suesu106 身邊兩個替死鬼嗎
tsaigwa41 非常建議戴耳機，第四次刷😊
husc1106 24.6.16
johnBitc 大哥沒有輸
jay6811 怎麼關閉彈幕
yunilc77 伊黑好帥
Shuhui0902 幹伊黑聲音超戳 低音炮？
gghij297 最右邊那個好像桐人
pir0680 2025/7/30 二刷!!
sunnyo0610 無一郎我老公！
b48103262 小芭內！！！！我愛你❤️
supreme888 ε٩(๑> ₃ <)۶з
xuankaiceng 不死川實彌我大哥
AdrianIsDead 廢城令，去高知城的時候導遊也是這麼說的
x2019184 2024/7/3
t132 五螞蟻！
ian101141 114/7/29簽到！
tsaigwa41 超帥
rumeitan461 2025／12／20簽到
s07143590000 小芭內好帥啊!
sk212233 路人鬼殺隊真帥
aliny54689 鬼滅之刃讚我最愛的是米豆子和炭治郎
s11009045 2026/8/2剛看刀匠 村篇的我
nervous0304 12.55
qh6ywhzgtt 彈幕很激動
Sophie1219 愛死伊黑😭😭😭
hongrry 這是金閃閃的聲音
s1120233 48分鐘X  4.8分鐘O
opsssu 2025.09.14
whu83939 2024.7.20 簽
whitecherryc 簽簽
ufggfg 好帥
GuanTC 1
five2k21 無一郎 我們來接你了！*^v^*
a86533774 不嗑童忍CP！！！
liamgong9454 工聯開跟速定位簽到！
Lynn8856 哈哈哈
nikki0413 我想看童磨
sunnyleea 二刷
aakk1221 好吵
dodylee0107 小忍忍我愛你❤️啾咪~
cindy960801 2025.7.22簽
line1031229 伊黑超帥聲音也好好聽
sunnyo0610 喔喔喔喔
ufggfg 我老公
sugarbady 五刷了！
hongrry 天守閣 影?
Blaze0011017 甚麼等級的鬼要出動兩名柱
suesu106 誰你老公啊
LAN106 小巴内
Sean6129pp 天守閣？ 將軍大人是你吧
aiheishasha 原神啟動！
yuzuzu1212 彈舌好聽
minnie991104 ２０２４．０７．１６
BHSN00000f8q 當然有啊就是無限城
sunnyleea ？？？？
sheila41000 耳機聽好讚
cxe1219 來回憶一下
pm4xftfc96 不死川我老公啊啊啊啊啊啊！(๑>◡<๑)
smallyhuang ;3
lyh227angel 耳機黨好爽_:(´ཀ`」 ∠):
hpjmsrcvqm 無限城到底什麼時候播
pennylady 彈出來了
young0411 看到他就想到爆豪
PIN041717 2024.11.17三刷簽*-*
xiecen 風柱越來越帥
st841513 八嘎
easontsai09 hi
ywu13765 有人嗎
rgnkzyvs8s 11/1簽到
rgshdfja ㄍㄍ
XHJ1104 最終大戰的戰響🔥🔥
fiddiin 三小
xin54081 2刷了 謝謝
yakawabaw 欸
xxx123xoxo 小芭內好可愛
yanghanchen3 不死川好帥!!!!!!!
m29296603 有夠好看
sheila41000 這背景音樂我愛了
sunnyleea Sb
slps105114 我一直以為主公是人
s0916ds 我也覺得很像爆豪
djdnndkzk 小芭內！！超帥
zigr10 我愛不死川😍
Rrtyuui92 我也看玩無限城了
syh0816 🦆🥩
aksndk 他有中文版的嗎
wanyan0803 Go go go!出發嘍
wowowoow 這段漫畫沒有喔 是上次電影上映時有的
Aa09833558 Sisisnksksks
slps105114 哈哈
eason107117 童魔：所以說我的外送到了沒
rgshdfja sb
dad666 有之狼那味
sunny031074 風柱會有彈舌音耶，やろrrrrr
Lockfox 小關和鈴村>///<
kazayaz 幫童磨打包消夜.jpg
lst20079 色
Asd820322 風柱帥炸
sunnyleea 伊黑小芭內的聲音很好聽
kwokcher616 原來風柱是ヤンキー
whitecherryc 漫畫沒有喔!
Zhmai773 打一個上玹一個柱  抓一個小鬼兩個柱
sey0204 裡面應該是豆西打
twjdnj 柱：解決什麼？
mashumao96 突然覺得這女生長的跟彌豆子好像ww
lichopin 甚麼規模要用動到兩根柱?
gghij297 不是你們打上弦派一個柱這種鬼你們派兩個柱
timhuang0513 火攻讓我想起DIO他家🤣
ian531182622 绑的不错
j0930e 大哥遇到上弦是意外
st841513 童磨
j0930e 這裡風蛇一起是設定上兩人剛好都有空(原創)
lst20079 色色
twjh108002 安安
s109071 無限城即將啟動
pocketmengo 兩個感覺是來送死的
AdrianIsDead 劍沒變色，呼吸法不熟練
s33456781 錯，是八集！
x1085104002 每一楨都好用心
husc1106   簽2024.6.16
yh220 依黑好帥哦
WJ728 三年前葦名城
XHJ1104 UFO我的超人😇🔥🔥
ufggfg 第八集最好看
s07143590000 小芭內我老公
sk212233 劇情普畫面神
whitecherryc 1:1:2
doggod 透透呢?
deadfall314 散兵～放個大招
esc360 鬼不是不能群聚嗎
AlexTo1008 前面的，鬼只要是接到無慘的命令就可以群聚
laboyz5586 英雄王怎麼沒有拿EA
b48103262 啊啊啊啊小芭內好帥啊啊啊啊啊啊
jia414227 牛
FantasyWhale 說好的鬼都單獨行動呢？
bilibala11 真的好美。。
yv237249 這麼帥的嗎？
line1031229 伊黑老公好帥
Giliang1260 這就是柱的實力
ufggfg 第八集最好看

chx19980620 島田源氏
ttttw7 是新的颜色
s109071 “成群結隊”的“狗”
Yyyyyu0126 實彌好帥🥹
c20121230 實彌好帥
lin8596lin 電影看效果更好+1
ytx981222 好看是好看但算不上神作、、
Hatura0221 其他隊員基本都在幹嘛的？
sugarbady 8/8號無限城上映！
yunilc77 小芭內好帥！！
Dravo41973 小打小鬧
owohyt 哈哈😁
qvcfv6yzkr 超帥
doggod 透透呢?
sk212233 路人好帥
XHJ1104 等等有風蛇柱戰鬥名場面！
b0983 鬼滅之刃是神作!
kiwi20060614 這段請戴耳機觀賞
yoyodaikinss ufo真的猛
Mrsmelon 風柱他弟更符合我口味
LEOR888999 吵死了
re668monster 自己覺得是神作就是神作
re668monster 沒必要去採一捧一
z999999op 哈哈，讚
WAnson2002 你們回去吧 誰都別想殺50隻鬼當柱
love5131030 伊黑的聲音聽起來真的很爽:3
tsaigwa41 意思是：滾回去，頂級傳話筒九塊九包郵到貨
areusick 風柱我老公🫶
bagel0327 ㄏ ㄏ ㄏ
fcbih350 京都人小芭內
pokjh684 不行，後面的劇情需要砲灰
o908326064 至少劇情沒咒術糟
ABCD90PQ 嗨
joyceph2579 一個翻譯一個講
st841513 那鬼爛死
DenItoi AwA
Hank150118 其實不是鬼太爛，而是柱太強了
Hank150118 其實不是鬼太爛      而是柱太強
rexxyz1234 只要不死就可以進鬼殺隊吧
rosa0812 帥
yanghanchen3 小川萬歲!!!!
tsaivickey 客觀來講不是神作 私心覺得是神作總行了吧
doggod 內內!
leesun0521 果然很礙事，小咖
yunilc77 聲音好好聽
haru5986 我愛你鈴村健一
utumakisusu 小內芭~~~~~~~~~~~~~~~~~~~~~~~~~~~
lst20079 🙈🙈
FeiFei88 香腸
hu2309111 蔣琬要不要也來一個😂
fy0814 BGM好好聽❤️
Ling48 殺字下隱約的滅字，好帥！
Kin730604 11
XHJ1104 🌀風之呼吸貳之型•爪爪科戶抓
cindyopop 看鬼滅都要帶耳機感受😁
whitecherryc 人家是1對1  它悶卻是2對1
sqxq7fqdz8 鐵碎牙www
nns0625518 這裡戴耳機，可以感受到風從左耳吹到右耳
xuan699149 BGM好屌
m29296603 還沒過半啦
AA9431 lossless scaling我用這個超順
stylexuan45 aaaa aaaa
Shuhui0902 特效拉滿
bua1211 曹操
ian101141 味全龍總冠軍！
little51322 2位都是溫柔的大哥哥，只是不善言辭QAQ
zxc882235555 風之傷
po971030 這裡耳機黨超爽
tt3331024 兄弟象爪爪
zxx424z229 爪爪爪爪馬
tiffanyliu90 switch!
Shigureui114 aoe就是爽啊
nz779rmv86 爪爪🤣
rayhao1103 好強喔
Giliang1260 蛇之呼吸 五之型 蜿蜒長蛇
hanhan0917 放隔壁棚就是兩個冠位C合力打鬼
love5131030 這個視角好帥！！！
ycq991016 爪馬馬馬馬
cook10226 哇是範圍技
kf067874 爪爪
flora53214 哇靠真的超帥
slps105114 終於
w201028 六歲肝塞拳
rosa0812 白蟑螂
claire101396 一個普通隊員在這殺了所有鬼是不是就能當柱
rgshdfja 爪爪
a18924842451 Aaaaaaaaaaaaaa
m29296603 啊啊啊啊啊好帥
benny0419ab 蜿蜿爪爪
wzb06200705  兩個的聲音都很好聽
XHJ1104 🐍蛇之呼吸伍之型•蜿蜒長蛇
b4y9vtf99 風柱如果對上可樂 風對風不知道會怎樣
soobin2000 爪爪
joyceph2579 好帥...
utumakisusu 好ㄘ~
zv6gyk8cfc 經費增加500萬
miyano177 小芭內好帥!!!!!!!!!!!
yh102298 帥死了
yunxin065 伊黑❤️❤️❤️
jinnachen999 好多疊字好可愛(՞˶･･˶՞)(՞˶･･˶՞)
qiuq0325 好像每篇九柱都會輪流出現
gigi88916 幽浮製作組我愛你…
Sa1234qqq 哈哈不死川好可愛
XIANGOWO 真的有像犬夜叉跟蛇骨 嘛耶童年！
fy0814 買周邊有錯嗎？有花你錢嗎？甘你屁事
wzb06200705 小巴內超帥
wyatt1020 生生流轉的衍生？
lst20079 好色
UnaMoco 留有人類時期癖好的鬼
Mrsmelon 不死川超帥
hinokiyama 太帥了>//////<
alicexyz2021 這表情和話到底誰是反派XDDD
rayhao1103 小巴內的操作好絲滑
minyanxi13 放開那個女孩
mi54567 蟑螂該死
dennis831021 不 死 川 砍 頭 妖 怪
Teodoro 到底誰比較像鬼
r5cqrtd6nn 一刀一個小朋友
b0983 鬼殺隊有時候的確很像反派
fy0814 這邊動作好順好讚
vm3503jo6 看個動畫彈幕釣出一堆潛在愉悅犯
mi54567 蟑螂去死
LHYlove0116 ㄒㄒ
qaz699578 可以不要說那幾個字嗎 我有陰影😱
a20050203 砍草
chris989292 增殖的G
Mrsmelon 割草遊戲
s0153444 小強🗿
IKraftIan1 擦經驗值
potatosb 想玩無雙的可以去玩鬼滅之刃火之神血風譚喔
asdzxc111205 下水餃
Shuhui0902 不愧是哈吸拉
aalin2w 風柱根本兵長
qiuq0325 段刀村是戀柱跟霞現在是風跟蛇
c7xthwf9mn 好刺激
wilson080666 蟑螂放大比鬼還強!？前面的給我回來解釋！
st841513 疑似像童磨童磨
rc8kt5zpkn 這真的像蟑螂
Xiang880930 有生怪磚  要插火把
lst20079 🪳🪳
twjdnj 長的跟炮灰一樣
JIAXUAN227 有刷怪籠（
Giliang1260 蛇之呼吸 參之型 扭曲的纏繞
star112999 因為吹捧就討厭一部作品 不懂呢
lunataker110 動畫本身就是毋庸置疑的上乘
miyano177 小芭內好帥ㄚㄚㄚㄚㄚㄚ
xiecen 好帥!!!
b0983 鬼滅的大家都好帥啊!!!
miantuan1007 我一直想到總悟
yuyu090321 神作
mi54567 蛇蛇😍
kim51610 伊黑小巴內
XHJ1104 🐍蛇之呼吸參之型•捲曲纏繞
milkcake0510 好帥
Zhmai773 小芭內好帥🥰🥰🥰
frank821118 不要wwwwwwwww
yunilc77 好帥
j0908530725 嗯？神似中文ww
jamyhighness 真後悔當初沒去電影院
ray950417 蛇柱的每招除了名子根本就一樣
wzb06200705 超帥
xihua 5是咬3是纏
lshzh301 風哥太老公了......
yupeko0525 帥死了！！！
joyceph2579 好帥我的天好帥
FAQYEE123 上屋頂是要打弦一朗嗎？
doggod 8+9
sodaxuan 電影院體感超讚
leilei82225 這跟我說跟小夫同一個聲優????wwwwwww
peiii21 好<3
crystal112 叫他去死的聲音也太帥。。。
Yxun9632 這看起來比較像要打義父
evawongem 爆豪？！
czann08 好我投降
Mrsmelon 戴耳機感覺這輩子都值了
kiwi20060614 不是...這兩位到底為什麼這麼帥啦!!!
leilei82225 這個側顏🤤🤤🤤
fy0814 這聲線……真的不是岡本啦差那麼多
GD20643796 我以為索隆又跑錯了
Zhmai773 大型果汁機
BHSN000015t5 風柱是關智一老師，金閃閃的CV
fpqgzvxfb7 下雨了
tmdrawj 黑繩大龍捲(誤
a902311670 神沙嵐
XHJ1104 🌀風之呼吸肆之型•昇上砂塵風
GD20643796 那麼多的鬼血 不小心舔到不會變鬼嗎
chx19980620 旋风
Akuma0114 血雨探花欸////
noone255 JoJo!
fy0814 回紅字，不會變，只有無慘的血才能讓人變鬼
zigr10 喔幹 水藍
喔幹 帥爛我沒了
Shuhui0902 番茄醬瀑布
una1010503 血與
chineyu0617 笑死 血肉果汁機
Zhmai773 大型果汁機😄
b0983 上弦之壹是不是也能讓人變鬼?
c123454244 血雨探花♥
fy0814 這邊講絕招名好帥
a902311670 jojo神沙嵐
yanghanchen3 血浴
a22221283 下一秒身上的血?
D0125S1002 原來招式名是可以打完再喊的嗎?
s0153444 這招式應該是血雨吧🤣
Shuhui0902 喔就桑媽 is time to go to bed
Sandy111800 下血了
ru0354ul4 瓦母烏
st841513 叫三小三小
ak20121128 前面血雨探花的站住XD
LikeOuO 血雨探花！！
lienhun1103 擋不住的大小姐
j1070049 我家老公真的好帥啊啊啊啊啊
FAQYEE123 牙類牙類
chineyu0617 再不睡覺 我們就要跳舞了喔
dkjkd13 呀勒呀勒？
wei81014 牙哩牙勒
Hatura0221 牙咧牙咧 攔不住的風柱大小姐
morris890071 真是調皮的大小姐啊
hongrry 大小姐 我們要起舞了
Shuhui0902 擋不住的大小姐
Xinyin70793 哈哈哈 大小姐www
Winnie0487 喜歡血的大小姐
Zhihan09 超屌
zxx424z229 呀咧呀咧 大少爺要砍刀了
po971030 呀勒呀勒
Sandy111800 下血
rb79520 牙勒牙勒～
rb79520 晚安大小姐～
mi54567 靠邀亞勒亞勒😂
Xinyin70793 お嬢様,It's time to go to bed.
b48103262 啊啊啊啊啊公主抱啊啊啊我也要！！！！！！
lcyg999 蜜璃平底鍋
miyano177 我也想被小芭內抱抱
sam40108 幹嘛用丟的 直接吃掉就好
wzes10021 我也想被抱
nyonyoxu1004 天啊我也要抱
peiyun0371 我也想當那個女生啊啊啊啊啊啊
jacy815 老公身體一定很香
Mrsmelon 我也要被抱
dkjkd13 英雄救美！帥爆
milkcake0510 蜜璃會吃醋的~
love5131030 哇反正最後都可能死怎麼不先弄死那女生:3
doggod :
yurei1018 我酸了
xyz120509836 他身上有蛇味 剛剛也被鬼的血噴到 確實香
Sophie1219 想當那個女生
flora53214 我也要被抱抱啊啊啊啊啊啊啊啊啊啊啊
baby97389 我的天 小芭內好帥RRRRRR
andrea731 公主抱+1
wzb06200705 戀柱來把那女的砍死
s109071 蜜璃會吃醋喔！小巴內
roy1001027 runner 仔
fifididirjdj 風柱身上的血呢？
lst20079 蜜璃會吃醋喔！小巴內
m29296603 下[血]了
Isjskana 刷副本刷到主線
Zhmai773 蜜璃：我失戀了💔
rosa0812 無限城
kikatsula 捅了蟑螂窩了
shes1050042 果然有詐
line1031229 我也要被抱
yinuan021 停停停为了救人蜜璃不会生气好吗，很难笑诶
chx19980620 無限城
peiyun0371 無限城!!
qxiao8204 你們是最早進無限城的
bj06150925 這個時候還是黃橘色的代表他們不會在這喪命
pinhuah30 🫣🫣
whitecherryc 那女生表示乾我屁事啊睡個覺也會出事
moonisme 差一點柱減二
Zhmai773 這裡是無限城，你們跳進去的話就死了
tps1116 不要進去啊進去就死了
odin890306 生骸村
fjc33 進入蟑螂窩
R814115 完了靠背
tshi606eggy 風柱不死川玄彌蛇柱伊黑小芭內提前進入副本
mi54567 乾真的好醜
sicconeuanda 無線城?
woodpig DLC上市前慘遭流出be like
m29296603 切真快
yunxin065 前幾天剛進電影院看無限城呢
qaz699578 直接進無限城副本
una1010503 無線城?!
MiMi1678 提醒：紅色才會死
b0983 本人表示:今天和家人一起去看無限城~
rosa0812 無限城！
st841513 噁
tswm7vmspv 無限城！
stanely0718 沒有足夠的玩家 戰場即將在5秒後關閉
csf201061 IKEA
s0153444 跳集喔🤣
Kin730604 111111
asd450502 回眸一笑
XHJ1104 最終戰役的敲響
wu0xji6n84 前方的區域 以後再來探索吧
fumaM 原地坐下也太可愛
Hatura0221 這刀品質也太好
fxckyouxpp 未滿足等級要求，無法進入
cindy960801 如果這個時候放進去這兩隻鬼殺隊就不會贏
qaz699578 人數不足，無法進入副本
ray123456987 123
love5131030 笑死出賣老巢
Tina104042 沒買會員啊
kevin771203 人數不足：一坪的無限城
tracyOWO 坐下好乖;)
deadfall314 隊伍等級不足，無法進入無限城深遠
Sa1234qqq 直接坐下好可愛啊啊啊啊
fy0814 出現Bug，將在3秒後關閉副本維修
lti1013 無慘記得隨手關燈
chris989292 這裡鳴女放他們進去就又少兩個柱
Zhmai773 人數不足 無法進入副本『無限城』
jasper7612 女生呢
woodpig 還好沒進去，要不然直接少兩個柱
qvcfv6yzkr 😅
N226958 人數不足哈哈哈
wrxmars 即將開啟主線最後一章
leilei82225 可愛小貓
wilson080666 還好沒進去欸  嚇死我啦
cook10226 此為總力戰副本，請招集更多玩家組隊~
sgreen970811 意外進副本的我 •́⁠ ⁠ ⁠‿⁠ ⁠,⁠•̀
ray123456987 KFC 好吃
rosa0812 人數不足 無法進入副本無限城
ee791031 Zzz
mary881020 哈哈鬼才知道
j0a2c1k4 1 !!
una1010503 無線城出現了>:3
j0a2c1k4 !!
Zhmai773 老婆
yuiytreete 611簽
tim876199 差點撞進最終副本
A20101017 714來這裡炭炭生日快樂
j0930e 香香～
tim876199 愣柱
azes82604 呃 這個車夫 好像是給炭炭 竹籃的那位
rgshdfja 再發自都是gay
peiyun0371 香奈乎~~🫶🏻
mi54567 美美噠🥰
Zhmai773 我老婆！！！
s7733262 老婆
kim51610 吾山上下呼
kim51610 吾山上下呼世晴
Blaze0011017 妳不回答我錶繼續跳喔
Zhmai773 介紹一下這是我老婆：栗花落 香奈乎
miku137 喋れよ！
A280140 公威阿
kim51610 我在山上山下都呼喊著世間應晴朗太平
audrey101125 美鋁請跟偶交往！
ZZ900611 ㄟ告
theyuan 神一般的英國管solo
fjc33 眼睛有點大
KJAE 20250808簽
a12640261047 為什麼沒有字
liyin0617 寶寶你說話很可愛ㄉ
cn5d2x2dn7 我願變成童話裡你愛的那故事裡
Zack501877 WRIP AG
rey20140312 蝴蝶人
x07070831 好正
PolarYu 經費車輪
sheila41000 下面紅字好好笑
s07143590000 跟第一季差好多
woodpig 連車輪都有夠細節
Sandy111800 不用睡了早上了
bboyordie 裙子真的變短了
a9462 胡蝶繼子們的墓碑嗎QQ
zfdzmv5hz8 阿是不會回話喔
spf7q 到底誰老婆拉
Zhmai773 藍字給我留下
cyharris816 今天開始 我要自己上廁所
lion0623 20250816簽
Emma09620420 沒有人磕童忍嗎
toto2245 這三個我老婆
s7733262 老婆的腳好香~~
assist0306 啞巴喔
zigr10 欸我真的不記得她們三個到底叫什麼：）
liyin0617 辛苦了寶寶
Zack501877 ＳＤＢ　Ｇ’ＺＳＢＤＩ　ＧＨ
a12640261047 有人可以翻譯一下嗎
chachamashum 我好想看香奈呼的呼吸法特效喔(⁠T⁠T⁠)
s207876 勇哥：（錯是我老婆）
xinyu1030208 2
b5qzfwjc4m 磕cp可以不要發出來嗎他們不是官配
tshi606eggy 還看得到小忍..我的老婆.
yichi0320 😍老婆😍
dodylee0107 我想看忍的小妹
mokamax 水池裡面銀龍魚
s207876 勇哥：（錯她是我老婆）
xjh1001206 老婆啊啊啊啊！
Zhmai773 我婆
hank20080801 根本我婆
evelyn055 漫畫善逸還把金魚搬去給禰豆子看被忍罵w
audrey101125 忍姐姐請速速與偶節芬！
bo47760 說義勇老婆的有點沒禮貌吧 他們不是官配
s109071 每個都老婆老公的真的是透透還是我老公如果
wshuaige22 細漢
angelinaku 窩老婆最可愛
ztdmjbj7s7 看完無限城再回來看好心痛💔
sicconeuanda 豆豆眼
dodylee0107 小忍忍養金魚
una1010503 金魚
asxdddd 塞乎，哇等來啊
Rita6146 回橘子真的……😭
Clps104057 有48分鐘喔？！
yang20130903 自然
J831 綾華跟甘雨(考哥警告)
yufanlin09 說香廢的是垃圾嗎🙄
xinyu1030208 6
Miunoko 便當便當
c5468607007 ˶ᵒ ᵕ ˂˶ //
UnaMoco 原P別跑！
f9368213 義忍是友情以上戀人未滿的官推
f9368213 這個沒什麼好爭議的吧
dodylee0107 哎呀
zx3899006 佐為原來你在這
whitecherryc 哇!頭柱的未婚妻
mwu507006 我愛看黃本
p81102002 胡蝶忍這個BGM Q_Q
game0407 喔不他也會死
a24302278 靠凹啊道貌岸然是負面成語別亂用==
XHJ1104 請支援蘿本！！
accord27321 看完無限城的我看到小忍真的忍不住😭😭
GrandPa87 感謝胡蝶忍的前情提要
s0153444 短裙MVP😍
deadfall314 日本的原神配音:)
fuhudifguf 淦腦袋裡都是綾華
cynthia36621 玄彌直接被無視
Wbread 玄彌：不是我也在場
speng4227 別劇透啊
liyin0617 寶寶！！
cynthia36621 玄彌勒
gfxjklfgjhg jo级生物
anandy1107 卡茲XDDDDDDDDDDD
Tina104042 玄彌:謝謝
YYYY8116777 恭喜！！
F887605056 回白字 395174
sgreen970811 怎麼感覺聲線怪怪的
jay139852430 啊啊啊啊 彌豆子好可愛😍💗💗💍
Josh1020101 彌豆子\(//∇//)\
ck6zj4jo6 以為在看狂賭之淵
jgjkxbpy9b 炭治郎一家吧彼岸花當野菜吃
ChairmanHuan 右下角耀光好評
ncbob 請用全國兵力保護..謝謝
jimmyyu 好久沒看到時透了啊～
ChairmanHuan 重點保護
cucu 如果能單獨把豆子拉到無限城就完事
a18924842451 wouoehn,a`hdkdgsyj`
enson780614 啊啊啊啊啊 全集中阿斯呼吸 ！
s1080725113 卡茲：我是成功了但我也停止思考了
Wguozoug 鬼頭要開始認真工作了
Aa1106028 一群戀童癖
ken062399 老婆~🤤🤤
whitecherryc 迷豆子好可愛喔!
liyin0617 寶寶好可愛啊啊
peiii21 對ㄟ48分鐘
liyin0617 正式開始上班超好笑
j0930e 砲你媽的灰 沒香奈乎配合 上二怎麼打
aa20120302 228922
tgs27xjgrd 我年紀都沒他們大我戀童💩？！
eshiu205 呀臘呀喇
joe10421 保護妳小姑?
abcd7849 保護小姑子
rexxyz1234 294320
henry580vip 現在白天無慘能過來才有鬼
rosa0812 好可愛！
una1010503 :3
dodylee0107 好可愛的小忍忍
N93130062 蝴蝶三姊妹
Nmsl9999 我心痛了
FAQYEE123 我沒了
soobin2000 好好看ㄛ
mqaz1030331 ：D
wuyuli511 眼睛都變好大顆..
nxbhm6tccd 超可愛！
game0407 我願意保護怎沒找我去
dodylee0107 哇啊
una1010503 加油
luweiyun1 為啥會有宿儺？？這不是咒術迴戰
shawn100801 228922
nick961209 忍好可愛
WeiHank0602 .
mwu507006 我打上弦二？
xxxxx1114 😨👺✌🏻
qqyingtang 古川慎！！
cjm1001 想看水柱
tigere EEEEEEEE
jackchou96 咒術完結
grace730609 我要看戀柱
badylin0807 你們好吵喔
yv237249 我要看霞柱！！！
Pupu0111 耶
syywnn024907 喔好愛炭炭
Yben56 應該算一隻 另一隻太爛了
orange2dei1 治郎太帥了
wxy0403 。。。
baconsteven 差點忘記那三隻的劇情
chuhuarung 實在很想知道產屋敷到底多有錢…………
elsa1229 要看透透
wmpwj4yq5w 呱～
jowen811020 問號鬼好萌ＸＤ
HEAVEN7 也要派一個柱守護村裡的人吧
BHSN000015t5 剛入隊的隊員每月薪資約莫等於20萬日幣
BHSN000015t5 柱階級的無限供應
ccc7632 他們家族做生意做1千年你說呢?w
znzxgwing 紫藤防鬼不防人.你敢讓人知道那是刀匠村?
ssss4714 很好奇這時候升到什麼等級了
WuYuFei0909 2026.4/26 三刷了
minhyun1296 戀柱:其實我今天也吃的不多
spf7q ?
hikitani8887 通稱海獺
s1080725113 三個相撲力士的飯量
alex686828 呱~
qxiao8204 甘露寺是個特殊體質
arielfu10206 痣是眼睛
asulan800212 多吃億點
rosa0812 神作啊
Ianlin0615 戀和霞睡了2天！！（羞）
Tychou0602 這翻譯
yy4rtdmd8v 五螞蟻
joe10421 真好 和戀小姐睡兩天wwwwww
tabasco1868 山田轉世
BHSN00002op0 原來是“蘇生”阿，靠這招恢復身體
qaz699578 柱都是變態
popat989 透透呢
bigppman89 可愛
snsd200916 這吃相第一次看到覺得好恐怖(￣▽￣)
s1120233 殺老師的吃(癡)像完美還原!!!!!
cjm1001 卻是吃很多
xiaojerry10 hi !
Cindy1031114 哈哈
xlin0482 變大哥了
fy0814 這季是最後的搞笑了要珍惜，後面刀超多
kk20001005 bgm也太強
a85584942 五賣
gigi88916 當初這段哭爛
kevin015p 超帥
spf7q 這聲音.....是奇預
rc8kt5zpkn 嗚嗚嗚嗚啊啊
syywnn024907 突然有刀
i2019 笑死 官方吐槽
gatling0515 麻吉雅巴庫內
h12454h 變成究極生物了
rosa0812 oi
syywnn024907 要哭的+2
kevinlin257 五條(X
martinivann awa
Sharon0212 幹真的跟五條的發音超像
evelyn055 不小心講出來XDD
l7856412 開門 麥當勞歡樂送
cindy0886 OI OI OI
kiwi20060614 成功轉移話題www
peter108128 oioioi
nrstommy4 差點被飯糰殺死 劇終
milazhang298 kgym
Alanyang2014 好看
rosa0812 oioioi
welcomedanny 破壞公物
ajayu50505 差點把珠世的事情說出來 才咽到的
a144878795 是他不能把珠世的事情說出去，這是約定
rosa0812 oioi
zxx424z229 眼睛很好看 挖出來吧
hz2157hzz 嗯嗯
Xm3h935p 48min好扯
wind7552116 畢竟鬼殺隊對鬼敵意很強 可能害到珠式
ypy0123 我的時透
yupeko0525 義勇寶寶😍😍😍
elsa1229 吃飯要專心~
yunilc77 透透！
hs310423 差點來不了
student3b01 oi
fy0814 現在回去看第一季的柱都像變了人～
xiemingzhi3 蜜璃老婆～
waxdr321 (人)
khzm27zrqh 嗨
s10an14dy 透透丫///
line1031229 我的蜜璃跟伊黑寶寶
luweiyun1 我的透寶
assist0306 屁孩透又來
tendou0322 48分鐘 !?
elsa1229 透透~~
yoyo93061211 靠杯他會道歉喔
yzx1227 ww 是透透
JFDJRR 唉呦
Redavt1114 哎呦
Blaze0011017 實彌你要不要點眼藥水
Cindy1031114 無一郎
spf7q 在大哥我就要關彈幕了
zxx424z229 炎柱不再 看起來沒人懷念ㄟ
Zian981013 宇髓呢
LZQCZY 小八內坐在老婆對面呢~~
adc250407 變八柱了
nb2txgv6pw 透透
xin813 老婆💗
Aaron3245 我婆密璃
fy0814 這個“叮”生雖才隔5年但好懷念
whitecherryc 飯都噴進茶裡了還喝
s0153444 可愛
nb2txgv6pw 我愛透透
a18924842451 oioioi
Kellycjjh 有人要吃醋了啦
melodycacvb 時透眼睛高光了!!!!!
doggod 透透!!
fy0814 眼睛炯炯有神的無一郎好可愛
wkry 好尬
phes50304m 好可愛(●°u°●)​
sunny031074 喔齁透透超卡哇♥️♥️
wpy1124 好可愛
luoluozijun5 透透！！
joyceph2579 透透我好愛你~~
s1900080808 好可愛(つД`)ノ
love5131030 無一郎真的好可愛wwww
y65014 刀放的位子真的很講究 XD
RayrayR0921 跟著炭治郎走就遇的到了
s109071 七柱⁉️
a44488055 沒事 你會遇到最強的
yuyang75031 這是不是照年紀坐的？
joanne9180 大哥你之後就遇到上一了啊！
yq7dg5kp5z 這是照身高坐嗎
hugotaylor35   別擔心你會遇到SSR
audrey101125 到時候無限城直接分到上一給你
R1000125 音柱嘞？
Rita6146 柱最後只剩兩個人好心痛😭
yunilc77 好帥
fles109023 時透出場時的彈幕最多耶～不愧是我老公
phes50304m 音柱是不是隱退？
line1031229 啊啊啊老公
fles109023 時透出場時的彈幕最多耶～真不愧是我老公
FAQYEE123 白蛇可以養嗎？
Sharon0212 你無一郎只是順便吧
audrey101125 到時候無限城直接給你分到上一你看鳴女多好
u1120643 時透只是拿來打掩護 目的只有蜜璃
PolarYu 其實只想問蜜璃吧蛇蛇^_^
fy0814 不會啦 喜歡歸喜歡 但對時透也是真關心
stu3395 這裏幫大家白話翻譯一下：蜜璃你沒事吧！
crystal112  每日一放閃
holaandworld 蜜璃寶寶可愛
wzes10021 戀愛腦！！
audrey101125 戀愛腦
sunny031074 結婚！！！！！
Tims99999 好可愛
zigr10 真的好想要他們兩個在一起 ༎ຶ⁠‿⁠༎ຶ
York2 會吃鬆餅
wmpwj4yq5w 蜜璃好可愛啊啊啊啊💗
Aa02240911 跟我暈船的反應一樣www
fles109023 時透講話感覺很嗆 前面都是前輩耶～
Aa02240911 好可愛
vivianya333 雙向暗戀?

- 標準格式
    - JSON格式: list+dict
    - CSV格式(Comma-Separtated Values)
        - 姓名,身高
        - Elwing,175
        - "Elwing, Mr. Chou",180

In [1]:
import json
import urllib.request as req
import pandas as pd

url = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=38250&geo=TW%2CHK"
f = req.urlopen(url)
content = f.read()
content = json.loads(content)
danmus = content["data"]["danmu"]
# pandas: DataFrame表格型態
df = pd.DataFrame(danmus)
df.to_csv("danmu.csv", encoding="utf-8", index=False)
df

                   text    color  size  position   time        sn       userid
0                     1  #FFFFFF     1         0      0  39929764   andy475713
1            2024.6.23簽  #FFFFFF     1         0      0  40108494     tcg19648
2                   簽🌭️  #FDE53D     1         0      0  40273436  shackle9487
3           2024/7/3冬雪簽  #FDE53D     2         0      0  40292119    naiyu0429
4               為何一直沒法看  #FFFFFF     1         0      0  42343409    gtkl20050
...                 ...      ...   ...       ...    ...       ...          ...
2996  這邊也好可愛😍 根本聖人狀態😍😍😍  #FFFFFF     0         2  29130  45144557     CCLEMONN
2997                 )(  #FF9496     2         2  29225  45144563     CCLEMONN
2998             大大大大大大  #B538FA     2         0  29231  39879325    FAQYEE123
2999         小學生可看不了呢老人  #FF0026     2         2  29389  46818174   h4kmg6snf2
3000        2025.7.29 *  #FFFFFF     1         0  29399  45902639      s935602

[3001 rows x 7 columns]

In [2]:
data = [
    {"name":"Elwing", "height":175},
    {"name":"Elwing, Mr. Chou", "height":180}
]
pd.DataFrame(data)

               name  height
0            Elwing     175
1  Elwing, Mr. Chou     180

- pandas兩大操作
    - 過濾: 準備一個跟你資料筆數依樣多的True(留下)/False(刪除)
    - 轉換: 準備一個函式, 參數就是原始資料,

In [3]:
# demo: 過濾(filter(fil))
fil = [True, False, True]
df.head(3)[fil]

  text    color  size  position  time        sn       userid
0    1  #FFFFFF     1         0     0  39929764   andy475713
2  簽🌭️  #FDE53D     1         0     0  40273436  shackle9487

In [6]:
s = "andy475713"
df["userid"] == s
df.head(3)[fil]

  text    color  size  position  time        sn       userid
0    1  #FFFFFF     1         0     0  39929764   andy475713
2  簽🌭️  #FDE53D     1         0     0  40273436  shackle9487

In [7]:
# demo: 轉換
# time
def func(n):
    return n + 100
df["time"].apply(func)

0         100
1         100
2         100
3         100
4         100
        ...
2996    29230
2997    29325
2998    29331
2999    29489
3000    29499
Name: time, Length: 3001, dtype: int64

In [9]:
# demo: 轉換
# color(HEX色碼->RGB code)
def func(s):
    s = s.replace("#", "")
    r, g, b = s[:2], s[2:4], s[4:]
    r, g, b = int(r, 16), int(g, 16), int(b, 16)
    return(r, g, b)
df["color"].apply(func)

0       (255, 255, 255)
1       (255, 255, 255)
2        (253, 229, 61)
3        (253, 229, 61)
4       (255, 255, 255)
             ...
2996    (255, 255, 255)
2997    (255, 148, 150)
2998     (181, 56, 250)
2999       (255, 0, 38)
3000    (255, 255, 255)
Name: color, Length: 3001, dtype: object